name: Deploy
description: Action For Vercel Deployment
inputs:
  VERCEL_TOKEN:
    description: "Vercel Token"
    required: true
  VERCEL_ORG_ID:
    description: "Vercel Organization ID"
    required: true
  VERCEL_PROJECT_ID:
    description: "Vercel Project ID"
    required: true
  VERCEL_ARGS:
    description: "Vercel Arguments"
    required: true
runs:
  using: "composite"
  steps:
    - name: Debug Vercel Args
      shell: bash
      run: echo Vercel args - ${{ inputs.vercel-args  }}
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ inputs.VERCEL_TOKEN }}
        vercel-org-id: ${{ inputs.VERCEL_ORG_ID }}
        vercel-project-id: ${{ inputs.VERCEL_PROJECT_ID }}
        vercel-args: ${{ inputs.VERCEL_ARGS }}
