name: Jest Test
description: Action for Jest Test
runs:
  using: "composite"
  steps:
    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: ~/.yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install
      shell: bash
    - name: Run Jest tests
      run: yarn jest
      shell: bash
