name: E2E Test
description: Action For E2E Test
inputs:
  CYPRESS_PROJECT_ID:
    description: "Cypress Project ID"
    required: true
  CYPRESS_RECORD_KEY:
    description: "Cypress Record Key"
    required: true
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: .
        install-command: yarn install
        command: yarn run --binaries-only cypress run
        build: yarn build
        start: yarn start
        wait-on: "http://localhost:3000"
        wait-on-timeout: 120
        record: true
        parallel: true
      env:
        CYPRESS_PROJECT_ID: ${{ inputs.CYPRESS_PROJECT_ID }}
        CYPRESS_RECORD_KEY: ${{ inputs.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
